#!/bin/bash

# gitlab-ci-multi-runner data directory
DATA_DIR="/etc/gitlab-runner"
CONFIG_FILE=${CONFIG_FILE:-$DATA_DIR/config.toml}

# launch gitlab-ci-multi-runner passing all arguments
exec gitlab-ci-multi-runner "$@"